### PR TITLE
III-5875 Embed contributers to uri

### PR DESCRIPTION
**Pull request by grubolsch**
### Changed
Added embedContributors GET param to URI to fetch document for indexing

---

Ticket: https://jira.uitdatabank.be/browse/III-5875

### CODE REVIEW

**Comment by grubolsch** [comment]
I am aware a unit test is broken, but I think the unit test is actually wrong in how the behavior should be.
The contributers should NOT be included in the originalEncodedJsonLd, because then everybody has access to it.

**Comment by LucWollants** [comment]
> I am aware a unit test is broken, but I think the unit test is actually wrong in how the behavior should be. The contributers should NOT be included in the originalEncodedJsonLd, because then everybody has access to it.

@grubolsch I think your assumption is correct.

**Comment by LucWollants** [comment]
@grubolsch but I also found this method `JsonLdPolyfillJsonTransformer::removeInternalProperties`

**Comment by grubolsch** [comment]
All feedback has been processed.

**Review by LucWollants — APPROVED** [review]

**Pull request merged**
