### PR TITLE
III-3934 - Use index 'no' instead of 'not-analyzed' to bypass the 32kb limit

### PR DESCRIPTION
**Pull request by jdrieghe**
### Fixed
- Some events with a very large JSON-LD representation did not get indexed properly
 
---
Ticket: https://jira.uitdatabank.be/browse/III-3934

### CODE REVIEW

**Review by LucWollants — APPROVED** [review]
Will this require a full replay?

**Comment by jdrieghe** [comment]
I think it's mostly to solve new documents already, but indeed. A re-index would not hurt I think.

**Comment by bertramakers** [comment]
Thanks for picking this up! You will also have to increment the schema version, otherwise the change won't be picked up even when we re-index (at least locally where we use an idempotent command that checks the version and only creates a new index if the version is different - maybe Kristof does it differently on acc/test/prod): https://github.com/cultuurnet/udb3-search-service/blob/main/src/ElasticSearch/Operations/SchemaVersions.php

**Comment by bertramakers** [comment]
And yes we will need a re-index, because the new mapping will only take effect when we create a new index with this mapping.

**Comment by jdrieghe** [comment]
@bertramakers done

**Review by bertramakers — APPROVED** [review]

**Pull request merged**
