### PR TITLE
III-5315 q=* behaviour on Organizer

### PR DESCRIPTION
**Pull request by JonasVHG**
### Added
 
- `OrganizerPredefinedQueryStringFields` to get set of predefined fields for `Organizer` & `UnitTest`
- Testfiles for `Organizer` with `description`
 
### Changed
 
- Added `DescriptionTransformer` in `OrganizerTransformer`
- Added `description` to `mapping_organizer.json`
- Added `OrganizerPredefinedQueryStringFields` to `ElasticSearchOrganizerQueryBuilder`
- Updated `UDB3_CORE` Version
- Updated `UnitTests` of `ElasticSearchOrganizerQueryBuilder` after inclusion of `PredefinedQueryStringFields`
- `UnitTest` for indexation in `OrganizerTransformerTest` for `Organizers` with `description`

---

Ticket: https://jira.uitdatabank.be/browse/III-5315

### CODE REVIEW

**Comment by LucWollants** [comment]
Should the `description` also be added to the allowed query parameters?
Is the indexation of `description` tested?

**Comment by JonasVHG** [comment]
> Should the `description` also be added to the allowed query parameters? Is the indexation of `description` tested?

1) No, the ticket was about the `q` parameter on `Organizer`, to bring it more in line with `Offer`.
`Offer` does not have a `description`-paramater so I would do the opposite of the ticket.
2) I've tested it locally on Docker.

**Comment by JonasVHG** [comment]
>  Is the indexation of `description` tested?
After some clarification via Slack a UnitTest is added to test indexation of `description` on `Organizers`

**Review by LucWollants — APPROVED** [review]
Nice work!

**Pull request merged**
